openapi: 3.1.0
info:
  title: Scissor API
  description: API for the URL shortening service
  version: 1.0.0
servers:
  - url: http://localhost:5003
    description: Local development server

paths:
  /api/urls/shorten:
    post:
      summary: Shorten a URL
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ShortenUrlRequest'
      responses:
        '201':
          description: Successfully shortened URL
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShortenUrlResponse'
        '400':
          description: Invalid input
        '500':
          description: Internal server error

  /api/urls/analytics/{shortUrl}:
    get:
      summary: Get analytics for a shortened URL
      parameters:
        - name: shortUrl
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Analytics data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AnalyticsResponse'
        '404':
          description: URL not found
        '500':
          description: Internal server error

  /api/urls/history:
    get:
      summary: Get URL history for the authenticated user
      responses:
        '200':
          description: List of URLs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/HistoryItem'
        '401':
          description: Unauthorized
        '500':
          description: Internal server error

components:
  schemas:
    ShortenUrlRequest:
      type: object
      properties:
        originalUrl:
          type: string
          format: uri
        customUrl:
          type: string
      required:
        - originalUrl

    ShortenUrlResponse:
      type: object
      properties:
        shortUrl:
          type: string
        qrCodeUrl:
          type: string

    AnalyticsResponse:
      type: object
      properties:
        clicks:
          type: integer
        originalUrl:
          type: string

    HistoryItem:
      type: object
      properties:
        originalUrl:
          type: string
        shortUrl:
          type: string
        qrCodeUrl:
          type: string
